// Copyright 2026 Han Wang. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CHROME_BROWSER_ABP_ABP_CONTROLLER_H_
#define CHROME_BROWSER_ABP_ABP_CONTROLLER_H_

#include <map>
#include <deque>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <vector>
#include <cstdint>

#include "base/files/file_path.h"
#include "base/memory/raw_ptr.h"
#include "base/memory/weak_ptr.h"
#include "base/observer_list.h"
#include "base/timer/timer.h"
#include "base/values.h"
#include "content/public/browser/devtools_agent_host.h"
#include "content/public/browser/devtools_agent_host_client.h"
#include "content/public/browser/render_widget_host.h"
#include "content/public/browser/render_widget_host_observer.h"
#include "content/public/browser/render_widget_host_view.h"
#include "content/public/browser/web_contents_observer.h"
#include "url/gurl.h"
#include "chrome/browser/abp/abp_curl_handler.h"
#include "chrome/browser/abp/abp_location_provider.h"
#include "chrome/browser/abp/abp_network_capture.h"
#include "chrome/browser/abp/abp_network_database.h"
#include "chrome/browser/abp/abp_permission_observer.h"
#include "chrome/browser/ui/tabs/tab_strip_model_observer.h"
#include "chrome/browser/abp/abp_action_context.h"
#include "chrome/browser/abp/abp_config.h"
#include "chrome/browser/abp/abp_types.h"
#include "third_party/skia/include/core/SkBitmap.h"
#include "ui/gfx/image/image.h"
#include "ui/base/cursor/mojom/cursor_type.mojom-forward.h"

namespace content {
class WebContents;
}

namespace abp {

class AbpActionContext;
class AbpConsoleCapture;
class AbpConsoleObserver;
class AbpDownloadObserver;
class AbpEventCollector;
class AbpEventObserver;
class AbpHistoryController;
class AbpInputDispatcher;
class AbpPopupInterceptor;

}  // namespace abp

namespace abp {

// Key information for CDP Input.dispatchKeyEvent
struct KeyInfo {
  KeyInfo();
  KeyInfo(const std::string& key,
          const std::string& code,
          int windows_virtual_key,
          int native_virtual_key,
          bool is_modifier,
          int modifier_flag);
  ~KeyInfo();
  KeyInfo(const KeyInfo&);
  KeyInfo& operator=(const KeyInfo&);

  std::string key;              // CDP key value (e.g., "Enter", "a")
  std::string code;             // CDP code value (e.g., "Enter", "KeyA")
  std::string text;             // Text generated by keypress (e.g., "\r" for Enter)
  int windows_virtual_key = 0;  // windowsVirtualKeyCode
  int native_virtual_key = 0;   // nativeVirtualKeyCode (same as windows on most platforms)
  bool is_modifier = false;     // true for Shift, Control, Alt, Meta
  int modifier_flag = 0;        // Modifier bitmask (1=Alt, 2=Ctrl, 4=Meta, 8=Shift)
};

// Get key info for CDP key event dispatch
// Returns info for the given key name (case-sensitive for letters)
KeyInfo GetKeyInfo(const std::string& key_name);

// Convert modifier names to CDP modifier bitmask
// Modifier names: "Alt", "Control", "Meta", "Shift"
int ModifiersToFlags(const std::vector<std::string>& modifiers);

// Normalize a key name for keyboard input.
// Uppercases the input, expands common abbreviations (Ctrl->CONTROL,
// Cmd/Meta->META, Opt->ALT, etc.), and validates against known keys.
// Returns the normalized key name, or nullopt if the key is not recognized.
std::optional<std::string> NormalizeKey(const std::string& input);

// CDP client for sending commands and receiving responses/events
class AbpCdpClient : public content::DevToolsAgentHostClient {
 public:
  using CdpCallback = base::OnceCallback<void(bool success,
                                               const std::string& result)>;
  using EventCallback = base::RepeatingCallback<void(const std::string& method,
                                                      const base::Value::Dict& params)>;

  explicit AbpCdpClient(scoped_refptr<content::DevToolsAgentHost> host);
  ~AbpCdpClient() override;

  AbpCdpClient(const AbpCdpClient&) = delete;
  AbpCdpClient& operator=(const AbpCdpClient&) = delete;

  // Send a CDP command and receive response via callback
  void SendCommand(const std::string& method,
                   const base::Value::Dict& params,
                   CdpCallback callback);

  // Set event listener for CDP events (replaces any existing listener)
  void SetEventListener(EventCallback callback);

  // Clear event listener
  void ClearEventListener();

  // DevToolsAgentHostClient implementation
  void DispatchProtocolMessage(content::DevToolsAgentHost* host,
                               base::span<const uint8_t> message) override;
  void AgentHostClosed(content::DevToolsAgentHost* host) override;

 private:
  scoped_refptr<content::DevToolsAgentHost> host_;
  int next_command_id_ = 1;
  std::map<int, CdpCallback> pending_callbacks_;
  EventCallback event_listener_;
  base::WeakPtrFactory<AbpCdpClient> weak_factory_{this};
};

// Per-tab observer for page lifecycle events during action waits.
// Uses WebContentsObserver (browser-side) instead of CDP Page domain events,
// which avoids race conditions with DevToolsSession message suspension during
// cross-process navigation.
class AbpPageLoadObserver : public content::WebContentsObserver {
 public:
  using LoadCallback = base::RepeatingCallback<void(const std::string& event)>;

  AbpPageLoadObserver(content::WebContents* wc, LoadCallback callback);
  ~AbpPageLoadObserver() override;

  AbpPageLoadObserver(const AbpPageLoadObserver&) = delete;
  AbpPageLoadObserver& operator=(const AbpPageLoadObserver&) = delete;

  // content::WebContentsObserver:
  void DOMContentLoaded(content::RenderFrameHost* render_frame_host) override;
  void DidFinishLoad(content::RenderFrameHost* render_frame_host,
                     const GURL& validated_url) override;
  void DidFirstVisuallyNonEmptyPaint() override;

 private:
  LoadCallback callback_;
};

// All available markup tags for screenshot overlays.
// None are enabled by default; clients pass the specific tags they want.
inline constexpr const char* kAllMarkupTags[] = {
    "clickable", "typeable", "scrollable", "grid", "selected"};
inline constexpr size_t kAllMarkupTagsCount = 5;

// Handles ABP REST API requests on the UI thread.
// Provides direct access to browser windows and tabs.
class AbpController : public TabStripModelObserver {
  // AbpActionContext needs access to execution control, history, and
  // screenshot methods to implement the unified action flow.
  friend class AbpActionContext;

  // AbpInputDispatcher needs access to GetOrCreateTabState for held key
  // tracking across KeyDown/KeyUp operations.
  friend class AbpInputDispatcher;

 public:
  AbpController();
  ~AbpController() override;

  AbpController(const AbpController&) = delete;
  AbpController& operator=(const AbpController&) = delete;

  // Test-only lifecycle observation for browser tests.
  // Fires at each action lifecycle transition. Null in production.
  enum class LifecycleStep {
    kResumeStarted,
    kResumeCompleted,
    kBeforeScreenshotStarted,
    kBeforeScreenshotCompleted,
    kActionExecuted,
    kWaitUntilCompleted,
    kScrollPositionReceived,
    kAfterScreenshotStarted,
    kAfterScreenshotCompleted,
    kPauseStarted,
    kPauseConfirmed,
    kPauseTimedOut,
    kResponseSent,
  };

  using LifecycleObserverCallback =
      base::RepeatingCallback<void(const std::string& tab_id,
                                   const std::string& action_type,
                                   LifecycleStep step)>;

  void SetLifecycleObserverForTesting(LifecycleObserverCallback cb);
  static AbpController* GetInstance();
  static AbpController* GetInstanceForTesting();

  // Validate markup tags — returns true if all tags are known.
  static bool ValidateMarkupTags(const std::vector<std::string>& tags,
                                 std::string* invalid_tag);

  // Wrappers for RenderWidgetHostImpl ForceRedraw test counters.
  // Avoids exposing content/browser internal headers to test code.
  static int GetForceRedrawQueuedCountForTesting();
  static void ResetForceRedrawCountersForTesting();

  // Result from CaptureActionScreenshot
  struct ActionScreenshotResult {
    ActionScreenshotResult();
    ~ActionScreenshotResult();
    ActionScreenshotResult(ActionScreenshotResult&&);
    ActionScreenshotResult& operator=(ActionScreenshotResult&&);

    std::string history_path;  // Path to saved file (empty if history disabled)
    std::string base64;        // Base64-encoded image data
    int width = 0;
    int height = 0;
    // Scroll position from compositor RenderFrameMetadata (after ForceRedraw).
    base::Value::Dict scroll_info;
  };
  using ActionScreenshotCallback =
      base::OnceCallback<void(ActionScreenshotResult)>;

  // Screenshot options struct (public for lambda access)
  struct ScreenshotOptions {
    ScreenshotOptions();
    ~ScreenshotOptions();
    ScreenshotOptions(const ScreenshotOptions&);
    ScreenshotOptions& operator=(const ScreenshotOptions&);

    std::string format = "png";      // png, jpeg, webp
    int quality = 80;                // 1-100 for jpeg/webp
    std::vector<std::string> markup_tags;  // clickable, typeable, scrollable, grid
    std::string mouse = "normal";    // normal, none, large
    bool cursor = true;              // Include virtual cursor in screenshot
  };

  // Set the history controller for action recording
  void SetHistoryController(AbpHistoryController* history_controller);

  // Set download observer (called by AbpHttpServer)
  void SetDownloadObserver(AbpDownloadObserver* observer);

  // Set event observer (called by AbpHttpServer, used to detach
  // event clients before closing tabs)
  void SetEventObserver(AbpEventObserver* observer);

  // Set session directory (called by AbpHttpServer, used for temp file storage)
  void SetSessionDir(const base::FilePath& session_dir);

  // Set timing configuration (called once at startup)
  void SetTimingConfig(const AbpConfig::TimingConfig& timing);

  // Get default action options with timing from config
  AbpActionContext::Options GetDefaultActionOptions() const;

  // Route incoming HTTP request to appropriate handler
  void HandleRequest(const std::string& method,
                     const std::string& path,
                     const std::string& body,
                     ResponseCallback callback);

  // Get the tab ID of the active tab in the first browser window
  // Returns empty string if no active tab is available
  std::string GetActiveTabId();

  // Get tab ID for a WebContents (lookup by DevToolsAgentHost ID)
  std::string GetTabIdForWebContents(content::WebContents* wc);

  // Emit a popup event (called by AbpPopupInterceptor)
  void EmitPopupEvent(const std::string& event_type,
                      base::Value::Dict event_data);

  // HTTP auth auto-dismiss notification (called by AbpLoginDelegate)
  void OnHttpAuthDismissed(const std::string& tab_id,
                           base::Value::Dict event_data);

  // Get popup interceptor
  AbpPopupInterceptor* popup_interceptor() { return popup_interceptor_.get(); }

  // Permission handling (called by AbpPermissionObserver)
  void OnPermissionRequested(const std::string& perm_id,
                             const std::string& tab_id,
                             const std::string& permission_type,
                             const std::string& origin);
  void OnPermissionDismissed(const std::string& perm_id,
                             const std::string& tab_id);

  // Permission API endpoints
  void ListPendingPermissions(ResponseCallback callback);
  void GrantPermission(const std::string& perm_id,
                       const base::Value::Dict& params,
                       ResponseCallback callback);
  void DenyPermission(const std::string& perm_id,
                      const base::Value::Dict& params,
                      ResponseCallback callback);

  // Permission observer accessor
  AbpPermissionObserver* permission_observer() {
    return permission_observer_.get();
  }

  // Center the virtual cursor in the viewport of the specified tab
  // Callback is invoked after cursor is centered (or on error)
  void CenterCursorInTab(const std::string& tab_id, base::OnceClosure callback);

  base::WeakPtr<AbpController> GetWeakPtr() {
    return weak_factory_.GetWeakPtr();
  }

  // Global input mode: agent (ABP-controlled) vs human (user-controlled).
  enum class InputMode {
    kAgent,
    kHuman,
    kCdp,
  };

  // Saved per-tab execution state for mode switch restore.
  struct SavedExecutionState {
    bool was_enabled = false;
    bool was_paused = false;
    double virtual_time_base_ms = 0.0;
  };

  // Input mode observer interface
  class InputModeObserver : public base::CheckedObserver {
   public:
    virtual void OnInputModeChanged(InputMode mode) = 0;
  };
  void AddInputModeObserver(InputModeObserver* observer);
  void RemoveInputModeObserver(InputModeObserver* observer);

  // Input mode accessors
  InputMode GetInputMode() const { return input_mode_; }
  void GetInputModeResponse(ResponseCallback callback);
  void SetInputMode(const base::Value::Dict& params,
                    ResponseCallback callback);

  // CDP mode: suspend ABP and start Chrome's remote debugging server
  void EnterCdpMode(const base::Value::Dict& params, ResponseCallback callback);
  void ExitCdpMode(ResponseCallback callback);

  // Check if browser is ready for ABP operations
  // Returns true if there's a browser window with a tab that has a valid view
  bool IsBrowserReady();

  // Get browser status for /api/v1/browser/status endpoint
  void GetBrowserStatus(ResponseCallback callback);

  // Get session data paths for /api/v1/browser/session-data endpoint
  void GetSessionData(ResponseCallback callback);

  // Helpers (public for use in lambdas)
  content::WebContents* FindWebContents(const std::string& tab_id);
  AbpCdpClient* GetOrCreateCdpClient(content::WebContents* wc);
  void SendError(int status,
                 const std::string& error,
                 ResponseCallback callback);
  void SendJson(int status,
                base::Value value,
                ResponseCallback callback);

  // Check if execution control is enabled (via command-line flag)
  bool IsExecutionControlEnabled() const;

  // Resume execution before action (Debugger.resume + virtual time advance)
  void ResumeExecution(const std::string& tab_id, base::OnceClosure then);

  // Pause execution after action (virtual time pause + Debugger.pause)
  void PauseExecution(const std::string& tab_id, base::OnceClosure then);

  // Force the compositor to paint a frame for the given tab.
  // Calls back when the frame is committed (or after 1500ms timeout).
  // Virtual time must be running (not paused) for this to work.
  void ForceRedrawForTab(const std::string& tab_id, base::OnceClosure then);

  // Fire-and-forget cleanup of markup overlays left from a previous action.
  // Reads and clears last_markup_tags from TabState.
  void CleanupMarkupForTab(const std::string& tab_id);

  // Pause execution on all open tabs (used at startup)
  void PauseAllTabs();

  // Release execution control on a tab that is losing focus.
  // Sets backgrounded=true, sends Debugger.disable + setVirtualTimePolicy("realtime").
  void BackgroundTab(const std::string& tab_id);

  // Re-establish execution control on a tab that is gaining focus.
  // Clears backgrounded=false, calls EnableExecutionControl if global flag is set.
  void ForegroundTab(const std::string& tab_id);

  // Wait for action_complete conditions before calling callback.
  // Three-phase wait: min_wait (JS hook window) → request tracking →
  // post-tracking settle. All durations configurable per action type.
  void WaitForActionComplete(
      const std::string& tab_id,
      base::OnceClosure on_complete,
      base::TimeDelta min_wait_time = base::Milliseconds(250),
      base::TimeDelta request_tracking_timeout = base::Seconds(1),
      base::TimeDelta post_tracking_settle_time = base::Milliseconds(750),
      bool page_was_loaded_before_action = false,
      bool all_requests = false,
      base::TimeDelta animation_wait_time = base::TimeDelta());

  // Wait for a specific condition before calling callback
  // Supports wait types: "text", "url", "network_idle", "time"
  void WaitFor(const std::string& tab_id,
               const base::Value::Dict& wait_params,
               base::OnceClosure on_complete);

  // Take screenshot for history (before or after action)
  // Uses direct C++ capture with CopyFromSurface
  // Note: Cursor is rendered by virtual cursor overlay and captured automatically
  void CaptureScreenshotForHistory(
      const std::string& tab_id,
      int64_t timestamp,
      bool is_before,
      base::OnceCallback<void(std::string path)> callback);

  // Capture screenshot for action context: injects markup CSS, captures via CDP,
  // cleans up CSS, saves to disk for history, and returns base64 + dimensions.
  // Serves both history and response purposes in a single capture.
  void CaptureActionScreenshot(
      const std::string& tab_id,
      int64_t timestamp,
      bool is_before,
      const ScreenshotOptions& options,
      ActionScreenshotCallback callback);

  // Capture screenshot from the current (frozen) screen buffer without
  // ForceRedraw.  Used for "before" screenshots while JS is still paused —
  // the compositor surface already contains the correct pixels.  No markup
  // injection (markup CSS cannot be painted without a redraw).
  void CaptureScreenshotFromBuffer(
      const std::string& tab_id,
      int64_t timestamp,
      bool is_before,
      const ScreenshotOptions& options,
      ActionScreenshotCallback callback,
      int retry_count = 0);

  // Update the virtual cursor state for a tab (used by input actions)
  void UpdateVirtualCursorState(const std::string& tab_id, double x, double y);

  // Set virtual cursor position via Mojo IPC for on-screen rendering
  void SetVirtualCursorViaMojo(content::WebContents* wc,
                                float x,
                                float y,
                                bool visible);

  // Enable/disable the virtual cursor system via Mojo IPC
  void SetVirtualCursorEnabledViaMojo(content::WebContents* wc, bool enabled);

  // Get virtual time for a tab, or wall clock if not enabled
  int64_t GetVirtualTimeMs(const std::string& tab_id);

  // Insert a deterministic visual-state fence for a tab.
  // Runs |callback| with true if a compositor frame boundary was reached.
  // Runs with false if the tab/widget is unavailable or the fence fails.
  void InsertVisualStateFence(const std::string& tab_id,
                              base::OnceCallback<void(bool)> callback);

  // Get the event collector (for AbpActionContext)
  AbpEventCollector* event_collector() { return event_collector_.get(); }

  // Called by event collector when a file chooser is opened
  void OnFileChooserOpened(const std::string& chooser_id,
                           const std::string& tab_id,
                           base::Value::Dict info);

  // Get scroll position for a tab via CDP (async)
  void GetScrollPosition(
      const std::string& tab_id,
      base::OnceCallback<void(base::Value::Dict)> callback);

  // Capture screenshot and return base64 data (for response envelope)
  void CaptureScreenshotBase64(
      const std::string& tab_id,
      base::OnceCallback<void(std::string base64, int width, int height)> callback);

  // Temporarily resume virtual time so the compositor can produce a frame.
  // The Debugger stays paused so no JS will run.
  // Call RestoreVirtualTimePause() after the screenshot to re-freeze.
  void EnsureCompositorActive(const std::string& tab_id,
                               base::OnceClosure callback);

  // Re-pause virtual time after a screenshot taken with EnsureCompositorActive.
  // No-op if virtual time wasn't paused.
  void RestoreVirtualTimePause(const std::string& tab_id,
                                base::OnceClosure callback);

 private:
  // TabStripModelObserver:
  void OnTabStripModelChanged(TabStripModel* tab_strip_model,
                              const TabStripModelChange& change,
                              const TabStripSelectionChange& selection) override;

  // Tab operations
  void ListTabs(ResponseCallback callback);
  void GetTab(const std::string& tab_id, ResponseCallback callback);
  void CreateTab(const base::Value::Dict& params, ResponseCallback callback);
  void CloseTab(const std::string& tab_id, ResponseCallback callback);

  // Navigation
  void Navigate(const std::string& tab_id,
                const base::Value::Dict& params,
                ResponseCallback callback);
  void Reload(const std::string& tab_id, ResponseCallback callback);
  void GoBack(const std::string& tab_id, ResponseCallback callback);
  void GoForward(const std::string& tab_id, ResponseCallback callback);

  // Content
  void Screenshot(const std::string& tab_id,
                  const base::Value::Dict& params,
                  ResponseCallback callback);
  void ExecuteScript(const std::string& tab_id,
                     const base::Value::Dict& params,
                     ResponseCallback callback);
  void GetText(const std::string& tab_id,
               const base::Value::Dict& params,
               ResponseCallback callback);

  // Input
  void Click(const std::string& tab_id,
             const base::Value::Dict& params,
             ResponseCallback callback);
  void Type(const std::string& tab_id,
            const base::Value::Dict& params,
            ResponseCallback callback);
  void Move(const std::string& tab_id,
            const base::Value::Dict& params,
            ResponseCallback callback);
  void Scroll(const std::string& tab_id,
              const base::Value::Dict& params,
              ResponseCallback callback);
  void Drag(const std::string& tab_id,
            const base::Value::Dict& params,
            ResponseCallback callback);
  void Slider(const std::string& tab_id,
              const base::Value::Dict& params,
              ResponseCallback callback);
  void ClearText(const std::string& tab_id,
                 const base::Value::Dict& params,
                 ResponseCallback callback);
  void KeyPress(const std::string& tab_id,
                const base::Value::Dict& params,
                ResponseCallback callback);
  void KeyDown(const std::string& tab_id,
               const base::Value::Dict& params,
               ResponseCallback callback);
  void KeyUp(const std::string& tab_id,
             const base::Value::Dict& params,
             ResponseCallback callback);

  // Tab control
  void ActivateTab(const std::string& tab_id, ResponseCallback callback);
  void StopLoading(const std::string& tab_id, ResponseCallback callback);

  // Utility actions
  void Wait(const std::string& tab_id,
            const base::Value::Dict& params,
            ResponseCallback callback);

  // Wait for all in-flight same-site network requests to settle.
  // Uses all_requests=true so requests from before wait started are tracked.
  // Timing: prewait=250ms, tracking_timeout=5s, post_settle=750ms.
  void WaitForNetwork(const std::string& tab_id,
                      const base::Value::Dict& params,
                      ResponseCallback callback);

  // Batch input actions (1-3 actions in a single action context)
  void HandleBatchRequest(const std::string& tab_id,
                          const base::Value::Dict& params,
                          ResponseCallback callback);

  // Execute validated batch actions within a single AbpActionContext
  void ExecuteBatchActions(const std::string& tab_id,
                           base::Value::List actions,
                           base::Value::Dict screenshot_config,
                           ResponseCallback callback);

  // File chooser endpoint
  void HandleFileChooser(const std::string& chooser_id,
                         const base::Value::Dict& params,
                         ResponseCallback callback);

  // Select popup endpoint
  void HandleSelectPopup(const std::string& popup_id,
                         const base::Value::Dict& params,
                         ResponseCallback callback);

  // Date/time picker endpoint
  void HandleDateTimePopup(const std::string& popup_id,
                           const base::Value::Dict& params,
                           ResponseCallback callback);

  // Run file chooser as a full ABP action (resume → set files → wait → pause)
  void RunFileChooserAction(const std::string& tab_id,
                            const std::string& chooser_id,
                            int backend_node_id,
                            std::vector<std::string> file_paths,
                            ResponseCallback callback);

  // Binary screenshot (GET endpoint - returns raw WebP)
  void BinaryScreenshot(const std::string& tab_id,
                        const std::string& query,
                        ResponseCallback callback);

  // Browser shutdown
  void ShutdownBrowser(const base::Value::Dict& params,
                       ResponseCallback callback);

  // Download endpoints
  void ListDownloads(const std::string& query, ResponseCallback callback);
  void GetDownloadStatus(const std::string& download_id,
                         ResponseCallback callback);
  void CancelDownload(const std::string& download_id,
                      ResponseCallback callback);
  void HandleDownloadContent(const std::string& download_id,
                             int64_t max_size,
                             ResponseCallback callback);

  // Network capture endpoints
  void HandleNetworkQuery(const std::string& query_string,
                          ResponseCallback callback);
  void HandleNetworkSave(const std::string& body, ResponseCallback callback);
  void HandleNetworkClear(const std::string& query_string,
                          ResponseCallback callback);
  void HandleCurl(const std::string& tab_id,
                  const std::string& body,
                  ResponseCallback callback);

  // Console capture endpoints
  void HandleConsoleQuery(const std::string& query_string,
                          ResponseCallback callback);
  void HandleConsoleClear(const std::string& query_string,
                          ResponseCallback callback);

  // Internal: capture step of CaptureActionScreenshot (after markup inject)
  // Uses GetSnapshotFromBrowser(from_surface=false) for ForceRedraw + capture.
  void CaptureActionScreenshotCdp(
      const std::string& tab_id,
      int64_t timestamp,
      bool is_before,
      const ScreenshotOptions& options,
      ActionScreenshotCallback callback,
      const base::FilePath& history_path,
      int view_width,
      int view_height);

  // Internal: screenshot capture using ForceRedrawWithCallback + GrabViewSnapshot.
  // ForceRedrawWithCallback queues automatically when blink_widget_ is null.
  void CaptureActionScreenshotWithRetry(
      const std::string& tab_id,
      int64_t timestamp,
      bool is_before,
      const ScreenshotOptions& options,
      ActionScreenshotCallback callback,
      const base::FilePath& history_path,
      int view_width,
      int view_height,
      int retry_count);

  // Forward declaration for ActionSnapState member.
  class ForceRedrawWatcher;

  // Shared state for action screenshot capture across async callbacks.
  struct ActionSnapState {
    ActionSnapState();
    ~ActionSnapState();
    bool done = false;
    ActionScreenshotCallback cb;
    ScreenshotOptions opts;
    base::FilePath h_path;
    std::string tab_id;
    base::TimeTicks force_redraw_start;
    std::shared_ptr<ForceRedrawWatcher> watcher;
  };

  // Watches an RWHI for destruction during an in-flight ForceRedraw.
  // If the RWHI is destroyed (cross-process navigation), triggers retry
  // on the new renderer's RWHI via OnForceRedrawRwhiDestroyed.
  class ForceRedrawWatcher : public content::RenderWidgetHostObserver {
   public:
    ForceRedrawWatcher(content::RenderWidgetHost* rwh,
                       base::WeakPtr<AbpController> controller,
                       std::shared_ptr<ActionSnapState> snap_state);
    ~ForceRedrawWatcher() override;

    // Unregister without triggering retry (normal completion path).
    void Cancel();

    // content::RenderWidgetHostObserver:
    void RenderWidgetHostDestroyed(
        content::RenderWidgetHost* widget_host) override;

   private:
    raw_ptr<content::RenderWidgetHost> rwh_;
    base::WeakPtr<AbpController> controller_;
    std::shared_ptr<ActionSnapState> snap_state_;
    bool cancelled_ = false;
  };

  // Called by ForceRedrawWatcher when the RWHI is destroyed mid-ForceRedraw.
  // Retries ForceRedraw on the new renderer's RWHI.
  void OnForceRedrawRwhiDestroyed(
      std::shared_ptr<ActionSnapState> snap_state);

  // Grab OS-level view snapshot with retry on blank/empty images.
  void GrabViewSnapshotWithFreshnessCheck(
      std::shared_ptr<ActionSnapState> snap_state,
      int retry_count);

  // Shared handler for action screenshot capture result (primary + fallback)
  void OnActionScreenshotCaptured(
      ActionScreenshotCallback callback,
      const ScreenshotOptions& options,
      const base::FilePath& history_path,
      const std::string& tab_id,
      const gfx::Image& snapshot);

  // ==========================================================================
  // Per-tab state types
  // ==========================================================================

  // Virtual cursor state - tracks cursor position for screenshots
  struct VirtualCursorState {
    bool active = false;
    double x = 0;
    double y = 0;
    ui::mojom::CursorType cursor_type = ui::mojom::CursorType::kPointer;
  };

  // Execution control state machine.
  // Transitions:
  //   kDisabled -> kPaused    (EnableExecutionControl)
  //   kPaused -> kResuming    (ResumeExecution called)
  //   kResuming -> kRunning   (Debugger.resume + virtual time resume confirmed)
  //   kRunning -> kPausing    (PauseExecution called)
  //   kPausing -> kPaused     (virtual time pause + Debugger.pause confirmed)
  //   any -> kDisabled        (tab close / cleanup)
  enum class ExecutionPhase {
    kDisabled,   // Execution control not enabled for this tab
    kPaused,     // JS halted + virtual time frozen
    kResuming,   // Resume in progress (CDP commands sent, awaiting callbacks)
    kRunning,    // JS running + virtual time advancing
    kPausing,    // Pause in progress (CDP commands sent, awaiting callbacks)
  };

  struct ExecutionState {
    ExecutionPhase phase = ExecutionPhase::kDisabled;
    double virtual_time_base_ticks_ms = 0;

    bool IsEnabled() const { return phase != ExecutionPhase::kDisabled; }
    bool IsPaused() const { return phase == ExecutionPhase::kPaused; }
    bool IsRunning() const { return phase == ExecutionPhase::kRunning; }
  };

  // Held keyboard keys state (for keyboard/down and keyboard/up)
  struct HeldKeyState {
    HeldKeyState();
    ~HeldKeyState();
    HeldKeyState(const HeldKeyState&);
    HeldKeyState& operator=(const HeldKeyState&);

    std::set<std::string> held_keys;  // Set of currently held key names
    int current_modifiers = 0;        // Bitmask of active modifiers (1=Alt, 2=Ctrl, 4=Meta, 8=Shift)
  };

  // Pending permission request state
  struct PendingPermissionRequest {
    PendingPermissionRequest();
    ~PendingPermissionRequest();
    PendingPermissionRequest(const PendingPermissionRequest&);
    PendingPermissionRequest& operator=(const PendingPermissionRequest&);

    std::string id;
    std::string tab_id;
    std::string permission_type;
    std::string origin;
    int64_t requested_at_ms = 0;
  };

  // Pending JavaScript dialog state
  struct PendingDialog {
    PendingDialog();
    ~PendingDialog();
    PendingDialog(const PendingDialog&);
    PendingDialog& operator=(const PendingDialog&);

    std::string dialog_type;   // "alert", "confirm", "prompt", "beforeunload"
    std::string message;
    std::string default_prompt;
    int64_t opened_at_ms = 0;
  };

  // Action complete wait state for after-screenshots
  // Default mode ("action_complete"): Waits for networkidle2 AND 500ms AND load AND DOMContentLoaded
  // Extended modes: "text", "url", "network_idle", "time"
  struct ActionCompleteWaiter {
    ActionCompleteWaiter();
    ~ActionCompleteWaiter();
    ActionCompleteWaiter(const ActionCompleteWaiter&) = delete;
    ActionCompleteWaiter& operator=(const ActionCompleteWaiter&) = delete;

    std::string tab_id;
    base::TimeTicks action_start_time;
    base::OnceClosure on_complete;

    // Wait type: "action_complete" (default), "text", "url", "network_idle", "time"
    std::string wait_type = "action_complete";

    // Condition flags for action_complete mode
    bool load_fired = false;
    bool dom_content_loaded_fired = false;
    bool first_paint_fired = false;
    bool network_idle = false;
    bool min_time_elapsed = false;
    bool min_wait_timer_started = false;
    bool animation_time_elapsed = false;
    bool animation_timer_started = false;

    // Observer for page lifecycle events (destroyed with waiter)
    std::unique_ptr<AbpPageLoadObserver> page_load_observer;

    // Network tracking (networkidle2 = ≤2 connections for 500ms)
    int active_requests = 0;
    base::TimeTicks last_network_activity;

    // Timeout
    base::TimeTicks timeout_time;
    uint64_t waiter_epoch = 0;  // Prevents stale timeouts from prior waiters

    // Minimum wait time (configurable per action)
    base::TimeDelta min_wait_time = base::Milliseconds(500);

    // Page registrable domain (eTLD+1) for same-site request filtering.
    // Only requests to this domain or its subdomains are tracked.
    std::string page_registrable_domain;

    // Request ID tracking (for action-triggered network requests)
    std::set<std::string> active_request_ids;        // all in-flight request IDs (filtered)
    std::set<std::string> tracked_requests;          // snapshot taken at min_wait boundary
    bool tracking_snapshot_taken = false;            // snapshot done
    bool tracked_requests_resolved = false;          // all tracked done or timed out
    bool tracking_timed_out = false;                 // timeout triggered (for event)
    base::TimeDelta request_tracking_timeout = base::Seconds(1);

    // Post-tracking settle (Phase 3)
    bool post_tracking_settle_started = false;
    bool post_tracking_settled = false;
    base::TimeDelta post_tracking_settle_time = base::Milliseconds(150);

    // If true, tracked_requests snapshot at prewait-end is seeded from the
    // tab's persistent_active_request_ids (all in-flight, not just since wait start).
    bool all_requests = false;

    // Text wait fields
    std::string wait_text;
    bool text_found = false;

    // URL wait fields
    std::string wait_url_pattern;
    bool url_matched = false;

    // Time wait fields (deferred: timer starts after page load)
    int time_wait_ms = 0;
    bool time_wait_started = false;
    bool time_wait_elapsed = false;

    bool IsComplete() const {
      if (wait_type == "action_complete") {
        bool animation_ok = !animation_timer_started || animation_time_elapsed;
        return load_fired && dom_content_loaded_fired &&
               first_paint_fired && min_time_elapsed &&
               tracked_requests_resolved && post_tracking_settled &&
               animation_ok;
      } else if (wait_type == "network_idle") {
        return network_idle;
      } else if (wait_type == "text") {
        return text_found;
      } else if (wait_type == "url") {
        return url_matched;
      } else if (wait_type == "time") {
        return time_wait_elapsed;
      }
      return false;
    }
  };

  // ==========================================================================
  // Consolidated per-tab state container
  // ==========================================================================

  // TabState holds all state associated with a single browser tab.
  // This consolidates what was previously 6 separate maps keyed by tab ID.
  struct TabState {
    TabState();
    ~TabState();
    TabState(TabState&&);
    TabState& operator=(TabState&&);
    TabState(const TabState&) = delete;
    TabState& operator=(const TabState&) = delete;

    // CDP client for DevTools protocol commands
    std::unique_ptr<AbpCdpClient> cdp_client;

    // Virtual cursor position and state
    VirtualCursorState cursor;

    // Execution control state (debugger, virtual time)
    ExecutionState execution;

    // Currently held keyboard keys
    HeldKeyState held_keys;

    // Pending JavaScript dialog (if any)
    std::optional<PendingDialog> pending_dialog;

    // Action completion waiter (for screenshot timing)
    std::unique_ptr<ActionCompleteWaiter> action_waiter;
    uint64_t next_waiter_epoch = 0;

    // Deterministic action loop state.
    bool action_in_flight = false;
    uint64_t active_action_epoch = 0;
    uint64_t next_action_epoch = 0;
    std::deque<base::OnceCallback<void(uint64_t)>> queued_action_starters;

    // True when this tab is not the active tab. Execution control is fully
    // released on backgrounded tabs. CDP callbacks in the execution control
    // chain check this flag and no-op if set.
    bool backgrounded = false;

    // Set when a tab switch happens during an action_in_flight (e.g., click
    // opened a new tab via window.open / target=_blank). The action context
    // reads and clears this in OnWaitUntilComplete to redirect its
    // after-screenshot and pause to the new tab.
    std::string tab_switched_to;

    // Persistent same-site network tracking (always-on, updated by CDP events).
    // Tracks in-flight request IDs regardless of whether a waiter is active.
    // Cleared on main-frame navigation. Used to seed browser_wait's snapshot.
    std::set<std::string> persistent_active_request_ids;
    std::string persistent_page_domain;  // eTLD+1 of current page for filtering

    // Pending callback for deterministic pause confirmation.
    // Set during PauseExecution, fired when Debugger.paused event arrives.
    base::OnceClosure pause_completion_callback;
    base::TimeTicks pause_event_wait_start;

    // Timer for pause confirmation timeout (safety net).
    // Wrapped in unique_ptr to keep TabState moveable.
    std::unique_ptr<base::OneShotTimer> pause_confirmation_timer;

    // Markup tags left on screen from the previous action's after-screenshot.
    // Read and cleared at the start of the next action's cleanup phase.
    std::vector<std::string> last_markup_tags;

    // Per-tab network capture buffer. Created lazily on first use.
    std::unique_ptr<AbpNetworkCapture> network_capture;

    // Check if tab has any active state
    bool IsIdle() const;

    // Reset all state (for cleanup)
    void Reset();
  };

  // All per-tab state, keyed by DevToolsAgentHost ID
  std::map<std::string, TabState> tab_states_;

  // Tab strip models we're observing for page-interaction tab opens.
  std::set<TabStripModel*> observed_tab_strips_;

  // Get or create TabState for a tab
  TabState& GetOrCreateTabState(const std::string& tab_id);

  // Clean up state for a closed tab
  void CleanupTabState(const std::string& tab_id);

  // Deterministic per-tab action runner.
  // Returns true if the action was started or queued, false if rejected
  // (queue full). Caller is responsible for sending 429 on rejection.
  bool RunOrQueueDeterministicAction(
      const std::string& tab_id,
      base::OnceCallback<void(uint64_t)> starter);
  void FinishDeterministicAction(const std::string& tab_id, uint64_t action_epoch);
  bool IsDeterministicActionCurrent(const std::string& tab_id,
                                    uint64_t action_epoch) const;

  static constexpr size_t kMaxQueuedActionsPerTab = 50;

  // ==========================================================================
  // Virtual cursor methods (private)
  // ==========================================================================

  // Sets the virtual cursor type via Mojo IPC.
  void SetVirtualCursorTypeViaMojo(content::WebContents* wc,
                                    ui::mojom::CursorType cursor_type);

  // Enable execution control (Debugger + virtual time) for a tab
  void EnableExecutionControl(
      const std::string& tab_id,
      std::optional<double> initial_virtual_time,
      base::OnceClosure then);

  // Get/Set execution state via REST endpoint
  void GetExecutionState(const std::string& tab_id, ResponseCallback callback);
  void SetExecutionState(const std::string& tab_id,
                         const base::Value::Dict& params,
                         ResponseCallback callback);

  // CDP callbacks for execution control
  void OnDebuggerEnabled(const std::string& tab_id,
                         std::optional<double> initial_virtual_time,
                         base::OnceClosure then,
                         bool success,
                         const std::string& result);
  void OnVirtualTimeEnabled(const std::string& tab_id,
                            base::OnceClosure then,
                            bool success,
                            const std::string& result);
  void OnVirtualTimeResumed(const std::string& tab_id,
                            base::OnceClosure then,
                            bool success,
                            const std::string& result);
  // Two-phase resume: Force a compositor frame while virtual time fences are
  // still up (fast, no task flood), then switch to realtime policy.
  void ForceRedrawThenResumeVirtualTime(const std::string& tab_id,
                                         base::OnceClosure then);
  // Helper: sends Emulation.setVirtualTimePolicy("realtime") and chains to
  // OnVirtualTimeResumed.
  void SwitchToRealtimeVirtualTime(const std::string& tab_id,
                                    base::OnceClosure then);
  void OnVirtualTimePaused(const std::string& tab_id,
                           base::OnceClosure then,
                           bool success,
                           const std::string& result);
  // Common deterministic pause sequence: Debugger.enable → Debugger.pause →
  // Runtime.evaluate("void 0") → wait for Debugger.paused event.
  // Used by both auto-pause (initial setup) and regular pause (action lifecycle).
  void SendDeterministicPause(const std::string& tab_id, base::OnceClosure then);
  void PauseVirtualTimeAfterDebugger(const std::string& tab_id, base::OnceClosure then);
  void EnableVirtualTimeAfterDebugger(const std::string& tab_id,
                                      std::optional<double> initial_virtual_time,
                                      base::OnceClosure then);
  void OnDebuggerPauseCommandSent(const std::string& tab_id,
                                  base::OnceClosure then,
                                  bool success,
                                  const std::string& result);
  void OnDebuggerPausedEvent(const std::string& tab_id);
  void OnPauseConfirmationTimeout(const std::string& tab_id);

  // Check if wait conditions are met and fire callback if so
  void CheckActionCompleteConditions(const std::string& tab_id);

  // Handle CDP events for action complete tracking
  void OnCdpEventForWait(const std::string& tab_id,
                         const std::string& method,
                         const base::Value::Dict& params);

  // Called when DidFirstVisuallyNonEmptyPaint fires during an action wait
  void OnPageLifecycleEvent(const std::string& tab_id,
                            const std::string& event);

  // Update persistent per-tab same-site network tracking.
  // Called on every CDP event regardless of waiter state.
  void OnPersistentNetworkEvent(const std::string& tab_id,
                                const std::string& method,
                                const base::Value::Dict& params);

  // Start the min_wait timer once all base conditions are met
  void MaybeStartMinWaitTimer(const std::string& tab_id);

  // Timer callback for minimum wait time (takes request tracking snapshot)
  void OnMinWaitTimeElapsed(const std::string& tab_id);
  void OnAnimationWaitTimeElapsed(const std::string& tab_id);

  // Timer callback for request tracking timeout (Phase 2 deadline)
  void OnRequestTrackingTimeout(const std::string& tab_id);

  // Timer callback for post-tracking settle (Phase 3)
  void OnPostTrackingSettle(const std::string& tab_id);

  // Timer callback for network idle check
  void OnNetworkIdleCheck(const std::string& tab_id);

  // Timer callback for wait timeout
  void OnWaitTimeout(const std::string& tab_id, uint64_t waiter_epoch);

  // Polling for text wait condition
  void OnTextPollCheck(const std::string& tab_id);
  void OnTextPollResult(const std::string& tab_id,
                        bool success,
                        const std::string& result);

  // Polling for URL wait condition
  void OnUrlPollCheck(const std::string& tab_id);

  // Deferred timer start for time wait (after page load)
  void OnLoadFiredForTimeWait(const std::string& tab_id);

  // Input mode switching
  void SwitchToHumanMode(ResponseCallback callback);
  void SwitchToAgentMode(ResponseCallback callback);
  void AbortActiveAction(const std::string& tab_id);
  void SetAllowSystemInputsForAllTabs(bool allow);

  // CDP mode helpers
  int FindAvailableCdpPort(int start_port, int max_attempts);
  void OnCdpModeTimeout();
  void DetachAllCdpClients();
  void ReattachAllCdpClients();

  // Dialog endpoint methods
  void GetDialog(const std::string& tab_id, ResponseCallback callback);
  void AcceptDialog(const std::string& tab_id,
                    const base::Value::Dict& params,
                    ResponseCallback callback);
  void DismissDialog(const std::string& tab_id, ResponseCallback callback);

  // Track dialog events from CDP
  void OnDialogOpened(const std::string& tab_id,
                      const std::string& dialog_type,
                      const std::string& message,
                      const std::string& default_prompt);
  void OnDialogClosed(const std::string& tab_id);

  // History controller (not owned)
  raw_ptr<AbpHistoryController> history_controller_ = nullptr;

  // Download observer (not owned - owned by AbpHttpServer)
  raw_ptr<AbpDownloadObserver> download_observer_ = nullptr;

  // Event observer (not owned - owned by AbpHttpServer)
  raw_ptr<AbpEventObserver> event_observer_ = nullptr;

  // Session directory for temp file storage
  base::FilePath session_dir_;

  // Network capture database (persists tagged requests to SQLite)
  std::unique_ptr<AbpNetworkDatabase> network_db_;

  // Curl handler (session-aware HTTP client)
  std::unique_ptr<AbpCurlHandler> curl_handler_;

  // Event collector for capturing events during actions (owned)
  std::unique_ptr<AbpEventCollector> event_collector_;

  // Input dispatcher for all input-related actions (owned)
  std::unique_ptr<AbpInputDispatcher> input_dispatcher_;

  // Pending file choosers (keyed by chooser ID)
  std::map<std::string, base::Value::Dict> pending_file_choosers_;

  // Popup interceptor for select dropdowns (owned)
  std::unique_ptr<AbpPopupInterceptor> popup_interceptor_;

  // Permission observer (owned)
  std::unique_ptr<AbpPermissionObserver> permission_observer_;

  // Console capture buffer (shared across all tabs)
  std::unique_ptr<AbpConsoleCapture> console_capture_;

  // Per-tab console observers (keyed by tab_id)
  std::map<std::string, std::unique_ptr<AbpConsoleObserver>> console_observers_;

  // Pending permission requests (keyed by permission ID)
  std::map<std::string, PendingPermissionRequest> pending_permissions_;

  // Test-only lifecycle observer callback. Null in production.
  LifecycleObserverCallback lifecycle_observer_for_testing_;

  // Build JavaScript for markup tag injection
  static std::string BuildMarkupInjectionScript(
      const std::vector<std::string>& markup_tags);
  // Build JavaScript for markup tag cleanup
  static std::string BuildMarkupCleanupScript(
      const std::vector<std::string>& markup_tags);

  // Static instance pointer for test access.
  static AbpController* instance_for_testing_;

  AbpConfig::TimingConfig timing_config_;

  // Global input mode state
  InputMode input_mode_ = InputMode::kAgent;
  std::map<std::string, SavedExecutionState> saved_execution_states_;
  base::ObserverList<InputModeObserver> input_mode_observers_;

  // CDP mode state
  int cdp_port_ = 0;                    // Active CDP server port (0 = not running)
  std::string cdp_bound_address_;       // Pre-test bound address (127.0.0.1 or [::1])
  std::string cdp_ws_url_;              // Full WebSocket URL for browser target
  std::shared_ptr<struct CdpBoundEndpoint> cdp_bound_endpoint_; // Actual bound endpoint from handler thread
  base::OneShotTimer cdp_timeout_timer_; // Auto-exit timer
  base::TimeTicks cdp_timeout_deadline_; // For remaining_ms calculation

  base::WeakPtrFactory<AbpController> weak_factory_{this};
};

}  // namespace abp

#endif  // CHROME_BROWSER_ABP_ABP_CONTROLLER_H_
