import("//build/config/features.gni")
import("//build/config/ui.gni")

source_set("abp") {
  sources = [
    "abp_action_context.cc",
    "abp_action_context.h",
    "abp_config.cc",
    "abp_config.h",
    "abp_controller.cc",
    "abp_controller.h",
    "abp_types.h",
    "abp_download_observer.cc",
    "abp_download_observer.h",
    "abp_event_collector.cc",
    "abp_event_collector.h",
    "abp_event_observer.cc",
    "abp_event_observer.h",
    "abp_history_controller.cc",
    "abp_history_controller.h",
    "abp_history_database.cc",
    "abp_history_database.h",
    "abp_http_server.cc",
    "abp_http_server.h",
    "abp_mcp_handler.cc",
    "abp_mcp_handler.h",
    "abp_switches.cc",
    "abp_switches.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/ui",
    "//chrome/common",
    "//components/download/public/common:public",
    "//components/version_info",
    "//content/public/browser",
    "//net",
    "//skia",
    "//sql",
    "//ui/base",
    "//ui/gfx",
    "//ui/gfx/geometry",
  ]

  if (use_aura) {
    deps += [ "//ui/aura" ]
  }
}
